In [20]:
import numpy as np
import matplotlib.pyplot as plt
%config InlineBackend.figure_format='retina'
import warnings
warnings.simplefilter('ignore')

Сгенерируем простой пример для наглядности:

In [21]:
X = np.array([[1, 1, 1, 1, 1,
               1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 
               0, 5, 10, 1, 2]]).T

In [22]:
X  # <- матрица "объекты-признаки" ([x0, x1])

array([[ 1,  1],
       [ 1,  1],
       [ 1,  2],
       [ 1,  1],
       [ 1,  3],
       [ 1,  0],
       [ 1,  5],
       [ 1, 10],
       [ 1,  1],
       [ 1,  2]])

In [23]:
X.shape

(10, 2)

In [24]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [25]:
y_pred1 = 45*np.ones(10) + X[:,1]*7
y_pred2 = 40*np.ones(10) + X[:,1]*8

2. Средняя абсолютная ошибка (MAE)

In [26]:
def calc_mae(y, y_pred):
    return np.mean(np.abs(y - y_pred))

3. Среднеквадратичная ошибка (MSE)

In [27]:
mse_1 = np.mean((y - y_pred1)**2)
mse_2 = np.mean((y - y_pred2)**2)
print(f'MSE наших моделей: {mse_1}, {mse_2}')

MSE наших моделей: 154.4, 188.6


In [28]:
def calc_mse(y, y_pred):
    return np.mean((y - y_pred)**2)

4. RMSE

In [29]:
rmse_1 = np.sqrt(np.mean((y - y_pred1)**2))
rmse_2 = np.sqrt(np.mean((y - y_pred2)**2))
print(f'MSE наших моделей: {rmse_1}, {rmse_2}')

MSE наших моделей: 12.425779653607254, 13.733171520082315


In [32]:
W = np.linalg.inv(np.dot(X.T, X)) @ X.T @ y
print(W)

[47.23214286  3.91071429]


In [33]:
# прогноз модели с оптимальными параметрами:
y_pred3 = W[0] + W[1]*X[:,1]
y_pred3

array([51.14285714, 51.14285714, 55.05357143, 51.14285714, 58.96428571,
       47.23214286, 66.78571429, 86.33928571, 51.14285714, 55.05357143])

In [34]:
calc_mse(y, y_pred3)

45.937499999999986

In [35]:
calc_mae(y, y_pred3)

6.182142857142856

In [36]:
W = np.array([0.01, 0.1])

In [37]:
y_pred = np.dot(X, W)
y_pred

array([0.11, 0.11, 0.21, 0.11, 0.31, 0.01, 0.51, 1.01, 0.11, 0.21])

In [38]:
calc_mse(y, y_pred)

3423.6233

In [39]:
lr = 0.01

In [40]:
grad_0 = (1/len(y))*lr*(2*np.sum(X[:,0]*(W[0]*X[:,0] - y)))
grad_1 = (1/len(y))*lr*(2*np.sum(X[:,1]*(W[1]*X[:,1] - y)))

In [41]:
W[0] = W[0] - grad_0; W[0]

1.1578

In [42]:
W[1] = W[1] - grad_1; W[1]

3.6688

In [43]:
y_pred = np.dot(X, W)
y_pred

array([ 4.8266,  4.8266,  8.4954,  4.8266, 12.1642,  1.1578, 19.5018,
       37.8458,  4.8266,  8.4954])

In [ ]:
calc_mse(y, y_pred)

### Домашнее задание:

1. Подберите скорость обучения (lr) и количество итераций (epoch):

In [61]:
n = X.shape[1]
epoch = 201
lr = 0.005
W = np.array([1, 0.5])
W, lr

(array([1. , 0.5]), 0.005)

In [62]:
W.shape[0]

2

In [63]:
for i in range(epoch):
    y_pred = np.dot(X, W)
    err = calc_mse(y, y_pred)
    for j in range(W.shape[0]):
        W[j] -= lr * (1/n * 2 * np.sum(X[:,j] * (y_pred - y)))
    if i % 50 == 0:
        print(f'# итерация: {i}, MSE: {err}, веса: {W}')

# итерация: 0, MSE: 3173.15, веса: [3.755 9.   ]
# итерация: 50, MSE: 121.00714874850121, веса: [35.72263172  6.03603356]
# итерация: 100, MSE: 51.32770226605233, веса: [44.14805163  4.48021532]
# итерация: 150, MSE: 46.32453098993166, веса: [46.40572907  4.06331791]
# итерация: 200, MSE: 45.96528986386297, веса: [47.01069683  3.95160599]


In [ ]:
#

*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

(array([1. , 0.5]), 0.005)

In [92]:
n = X.shape[1]
epoch = 301
lr = 0.005
W = np.array([1, 0.5])
W, lr
for i in range(200):
    y_pred = np.dot(X, W)
    err = calc_mse(y, y_pred)
    #print(y_pred - y)
    Y = y_pred - y
    Y = Y[:, None]
    #print(Y)
#     for j in range(W.shape[0]):
#   W[j] -= lr * (1/n * 2 * np.sum(X[:, j] * (y_pred - y)))
    W -= (lr * (1/n * 2 * np.sum(X*Y)))
    if i % 50 == 0:
        print(f'# итерация: {i}, MSE: {err}, веса: {W}')

# итерация: 0, MSE: 3173.15, веса: [12.255 11.755]
# итерация: 50, MSE: 737.091826923077, веса: [11.82211538 11.32211538]
# итерация: 100, MSE: 737.091826923077, веса: [11.82211538 11.32211538]
# итерация: 150, MSE: 737.091826923077, веса: [11.82211538 11.32211538]


Видно, что от ошибки избавился, но результат получается другой

In [ ]:
Y

In [ ]:
y_pred-y

Задание **3: вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию начинает изменяться ниже определенного порога

In [59]:
MIN_CHANGE = 0.01

In [60]:
#
last_err =10**5
epoch = 1
lr = 0.005
W = np.array([1, 0.5])
while True:
        
    y_pred = np.dot(X, W)
    err = calc_mse(y, y_pred)
    if err < last_err - MIN_CHANGE:
        #print(epoch, err)
        for j in range(W.shape[0]):
            W[j] -= lr * (1/n * 2 * np.sum(X[:,j] * (y_pred - y)))
        if epoch % 50 == 0:
            print(f'# итерация: {epoch}, MSE: {err}, веса: {W}')
        
    else:
        print(f'# итерация: {epoch}, MSE: {err}, веса: {W}')
        break
        
    epoch += 1
    last_err = err
    

# итерация: 50, MSE: 125.0675737025576, веса: [35.41546297  6.09275462]
# итерация: 100, MSE: 51.6192516758786, веса: [44.06574262  4.49541431]
# итерация: 150, MSE: 46.34546502007181, веса: [46.38367353  4.06739064]
# итерация: 166, MSE: 46.11312564988714, веса: [46.66058888  4.0162561 ]
